// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {
  "new-york": {
    "Authentication01": {
      name: "Authentication01",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication01.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication02": {
      name: "Authentication02",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication02.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication03": {
      name: "Authentication03",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication03.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication04": {
      name: "Authentication04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication04.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard01": {
      name: "Dashboard01",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","badge","button","card","dropdown-menu","input","sheet","table"],
      files: [{
        path: "registry/new-york/block/Dashboard01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard01.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard02": {
      name: "Dashboard02",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","card","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/new-york/block/Dashboard02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard02.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard03": {
      name: "Dashboard03",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","drawer","input","label","select","textarea","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard03.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard04": {
      name: "Dashboard04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","checkbox","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/new-york/block/Dashboard04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard04.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard05": {
      name: "Dashboard05",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","checkbox","dropdown-menu","input","pagination","progress","separator","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard05.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard05.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard05.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard05.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard06": {
      name: "Dashboard06",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard06.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard06.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard06.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard06.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard07": {
      name: "Dashboard07",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","label","select","sheet","table","textarea","toggle-group","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard07.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard07.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard07.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard07.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar01": {
      name: "Sidebar01",
      description: "",
      type: "registry:block",
      registryDependencies: ["breadcrumb","dropdown-menu","label","separator","sidebar"],
      files: [{
        path: "registry/new-york/block/Sidebar01/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Sidebar01/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Sidebar01/page.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Sidebar01/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar02": {
      name: "Sidebar02",
      description: "",
      type: "registry:block",
      registryDependencies: ["AppSidebar.vue","breadcrumb","separator","sidebar","SearchForm.vue","VersionSwitcher.vue","collapsible","label","dropdown-menu"],
      files: [{
        path: "registry/new-york/block/Sidebar02/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Sidebar02/page.vue?raw").then((m) => m.default)
      },{
        path: "registry/new-york/block/Sidebar02/components/AppSidebar.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/new-york/block/Sidebar02/components/AppSidebar.vue?raw").then((m) => m.default)
      },{
        path: "registry/new-york/block/Sidebar02/components/SearchForm.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/new-york/block/Sidebar02/components/SearchForm.vue?raw").then((m) => m.default)
      },{
        path: "registry/new-york/block/Sidebar02/components/VersionSwitcher.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/new-york/block/Sidebar02/components/VersionSwitcher.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Sidebar02/page.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Sidebar02/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar07": {
      name: "Sidebar07",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","breadcrumb","collapsible","dropdown-menu","separator","sidebar"],
      files: [{
        path: "registry/new-york/block/Sidebar07/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Sidebar07/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Sidebar07/page.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Sidebar07/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication01": {
      name: "Authentication01",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication01.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication02": {
      name: "Authentication02",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication02.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication03": {
      name: "Authentication03",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication03.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication04": {
      name: "Authentication04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/new-york/block/Authentication04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Authentication04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Authentication04.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Authentication04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard01": {
      name: "Dashboard01",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","badge","button","card","dropdown-menu","input","sheet","table"],
      files: [{
        path: "registry/new-york/block/Dashboard01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard01.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard02": {
      name: "Dashboard02",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","card","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/new-york/block/Dashboard02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard02.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard03": {
      name: "Dashboard03",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","drawer","input","label","select","textarea","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard03.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard04": {
      name: "Dashboard04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","checkbox","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/new-york/block/Dashboard04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard04.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard05": {
      name: "Dashboard05",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","checkbox","dropdown-menu","input","pagination","progress","separator","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard05.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard05.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard05.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard05.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard06": {
      name: "Dashboard06",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard06.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard06.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard06.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard06.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard07": {
      name: "Dashboard07",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","label","select","sheet","table","textarea","toggle-group","tooltip"],
      files: [{
        path: "registry/new-york/block/Dashboard07.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Dashboard07.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Dashboard07.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Dashboard07.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar01": {
      name: "Sidebar01",
      description: "",
      type: "registry:block",
      registryDependencies: ["breadcrumb","dropdown-menu","label","separator","sidebar"],
      files: [{
        path: "registry/new-york/block/Sidebar01/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Sidebar01/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Sidebar01/page.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Sidebar01/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar02": {
      name: "Sidebar02",
      description: "",
      type: "registry:block",
      registryDependencies: ["AppSidebar.vue","breadcrumb","separator","sidebar","SearchForm.vue","VersionSwitcher.vue","collapsible","label","dropdown-menu"],
      files: [{
        path: "registry/new-york/block/Sidebar02/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Sidebar02/page.vue?raw").then((m) => m.default)
      },{
        path: "registry/new-york/block/Sidebar02/components/AppSidebar.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/new-york/block/Sidebar02/components/AppSidebar.vue?raw").then((m) => m.default)
      },{
        path: "registry/new-york/block/Sidebar02/components/SearchForm.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/new-york/block/Sidebar02/components/SearchForm.vue?raw").then((m) => m.default)
      },{
        path: "registry/new-york/block/Sidebar02/components/VersionSwitcher.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/new-york/block/Sidebar02/components/VersionSwitcher.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Sidebar02/page.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Sidebar02/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar07": {
      name: "Sidebar07",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","breadcrumb","collapsible","dropdown-menu","separator","sidebar"],
      files: [{
        path: "registry/new-york/block/Sidebar07/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/new-york/block/Sidebar07/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/new-york/block/Sidebar07/page.vue").then((m) => m.default),
      raw: () => import("@/registry/new-york/block/Sidebar07/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
  },  "default": {
    "Authentication01": {
      name: "Authentication01",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/Authentication01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication01.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication02": {
      name: "Authentication02",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/Authentication02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication02.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication03": {
      name: "Authentication03",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/Authentication03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication03.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication04": {
      name: "Authentication04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/default/block/Authentication04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication04.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard01": {
      name: "Dashboard01",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","badge","button","card","dropdown-menu","input","sheet","table"],
      files: [{
        path: "registry/default/block/Dashboard01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard01.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard02": {
      name: "Dashboard02",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","card","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/default/block/Dashboard02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard02.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard03": {
      name: "Dashboard03",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","drawer","input","label","select","textarea","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard03.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard04": {
      name: "Dashboard04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","checkbox","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/default/block/Dashboard04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard04.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard05": {
      name: "Dashboard05",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","checkbox","dropdown-menu","input","pagination","progress","separator","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard05.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard05.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard05.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard05.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard06": {
      name: "Dashboard06",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard06.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard06.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard06.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard06.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard07": {
      name: "Dashboard07",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","label","select","sheet","table","textarea","toggle-group","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard07.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard07.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard07.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard07.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar01": {
      name: "Sidebar01",
      description: "",
      type: "registry:block",
      registryDependencies: ["breadcrumb","dropdown-menu","label","separator","sidebar"],
      files: [{
        path: "registry/default/block/Sidebar01/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Sidebar01/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Sidebar01/page.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Sidebar01/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar02": {
      name: "Sidebar02",
      description: "",
      type: "registry:block",
      registryDependencies: ["AppSidebar.vue","breadcrumb","separator","sidebar","SearchForm.vue","VersionSwitcher.vue","collapsible","label","dropdown-menu"],
      files: [{
        path: "registry/default/block/Sidebar02/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Sidebar02/page.vue?raw").then((m) => m.default)
      },{
        path: "registry/default/block/Sidebar02/components/AppSidebar.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/default/block/Sidebar02/components/AppSidebar.vue?raw").then((m) => m.default)
      },{
        path: "registry/default/block/Sidebar02/components/SearchForm.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/default/block/Sidebar02/components/SearchForm.vue?raw").then((m) => m.default)
      },{
        path: "registry/default/block/Sidebar02/components/VersionSwitcher.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/default/block/Sidebar02/components/VersionSwitcher.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Sidebar02/page.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Sidebar02/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar07": {
      name: "Sidebar07",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","breadcrumb","collapsible","dropdown-menu","separator","sidebar"],
      files: [{
        path: "registry/default/block/Sidebar07/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Sidebar07/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Sidebar07/page.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Sidebar07/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication01": {
      name: "Authentication01",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/Authentication01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication01.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication02": {
      name: "Authentication02",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/Authentication02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication02.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication03": {
      name: "Authentication03",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/Authentication03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication03.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Authentication04": {
      name: "Authentication04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/default/block/Authentication04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Authentication04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Authentication04.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Authentication04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard01": {
      name: "Dashboard01",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","badge","button","card","dropdown-menu","input","sheet","table"],
      files: [{
        path: "registry/default/block/Dashboard01.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard01.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard01.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard01.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard02": {
      name: "Dashboard02",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","card","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/default/block/Dashboard02.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard02.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard02.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard02.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard03": {
      name: "Dashboard03",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","button","drawer","input","label","select","textarea","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard03.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard03.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard03.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard03.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard04": {
      name: "Dashboard04",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","checkbox","dropdown-menu","input","sheet"],
      files: [{
        path: "registry/default/block/Dashboard04.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard04.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard04.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard04.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard05": {
      name: "Dashboard05",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","checkbox","dropdown-menu","input","pagination","progress","separator","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard05.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard05.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard05.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard05.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard06": {
      name: "Dashboard06",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","sheet","table","tabs","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard06.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard06.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard06.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard06.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Dashboard07": {
      name: "Dashboard07",
      description: "",
      type: "registry:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","label","select","sheet","table","textarea","toggle-group","tooltip"],
      files: [{
        path: "registry/default/block/Dashboard07.vue",
        type: "registry:block",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Dashboard07.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Dashboard07.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Dashboard07.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar01": {
      name: "Sidebar01",
      description: "",
      type: "registry:block",
      registryDependencies: ["breadcrumb","dropdown-menu","label","separator","sidebar"],
      files: [{
        path: "registry/default/block/Sidebar01/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Sidebar01/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Sidebar01/page.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Sidebar01/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar02": {
      name: "Sidebar02",
      description: "",
      type: "registry:block",
      registryDependencies: ["AppSidebar.vue","breadcrumb","separator","sidebar","SearchForm.vue","VersionSwitcher.vue","collapsible","label","dropdown-menu"],
      files: [{
        path: "registry/default/block/Sidebar02/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Sidebar02/page.vue?raw").then((m) => m.default)
      },{
        path: "registry/default/block/Sidebar02/components/AppSidebar.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/default/block/Sidebar02/components/AppSidebar.vue?raw").then((m) => m.default)
      },{
        path: "registry/default/block/Sidebar02/components/SearchForm.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/default/block/Sidebar02/components/SearchForm.vue?raw").then((m) => m.default)
      },{
        path: "registry/default/block/Sidebar02/components/VersionSwitcher.vue",
        type: "registry:component",
        target: "",
        raw: () => import("@/registry/default/block/Sidebar02/components/VersionSwitcher.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Sidebar02/page.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Sidebar02/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
    "Sidebar07": {
      name: "Sidebar07",
      description: "",
      type: "registry:block",
      registryDependencies: ["avatar","breadcrumb","collapsible","dropdown-menu","separator","sidebar"],
      files: [{
        path: "registry/default/block/Sidebar07/page.vue",
        type: "registry:page",
        target: "pages/dashboard/index.vue",
        raw: () => import("@/registry/default/block/Sidebar07/page.vue?raw").then((m) => m.default)
      }],
      component: () => import("@/registry/default/block/Sidebar07/page.vue").then((m) => m.default),
      raw: () => import("@/registry/default/block/Sidebar07/page.vue?raw").then((m) => m.default),
      source: "",
      category: "",
      subcategory: ""
    },
  },
}

